apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: filipem/eureka-service:1.1.0
          ports:
            - containerPort: 8761
          volumeMounts:
            - name: eureka-config
              mountPath: /config/application.yaml
              subPath: application.yaml
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"
      volumes:
        - name: eureka-config
          configMap:
            name: eureka-config
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort