apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-admin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-admin-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec","secrets"]
    verbs: ["get","create" ,"update" ,"patch" ,"delete" , "list", "watch", "exec"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-admin-binding
subjects:
  - kind: ServiceAccount
    name: elastic-admin
roleRef:
  kind: Role
  name: elastic-admin-role
  apiGroup: rbac.authorization.k8s.io
