{{- range $name, $account := .Values.accounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
---
{{- range $foo, $role := $account.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $role }}-{{ $name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
roleRef:
  kind: Role
  name: {{ $role }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}