{{- range $name, $secret := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
type: Opaque
stringData:
{{- range $i, $val := $secret }}
  {{ $i }}: {{ $val }}
{{- end }}
---
{{- end }}
