#Service name used for logging
service:
    name: Gamecatalog

#Server Configuration
server:
    port: 9094
    error:
        include-message: always

spring:
    application:
        name: GAME-CATALOG-SERVICE
    #Database Configuration
    datasource:
        url: jdbc:postgresql://${DATABASE_URL}/games
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    #Kafka connection
    kafka:
        bootstrap-servers: ${KAFKA_SERVER_ADDRESS:http://localhost:9092}
    # Security Configuration
    security:
        oauth2:
          resourceserver:
            jwt:
                issuer-uri: ${JWT_ISSUER_URI}
                jwk-set-uri: ${JWT_ISSUER_URI}/protocol/openid-connect/certs

#Eureka Configuration
eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_ADDRESS}

#JWT Configuration
jwt:
    auth:
        converter:
            resource-id: keycloak-client
            principal-attribute: preferred_username

#Logging levels
logging:
    level:
        org.apache.kafka: ERROR


#Rollbar Configuration
rollbar:
    accessToken: ${ROLLBAR_TOKEN}
