apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
data:
  elasticsearch.yml: |
    xpack.security.enabled: true
    discovery.type: single-node

    network.host: 0.0.0.0
    http.port: 9200

    xpack.security.http.ssl:
      enabled: true
      key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
      certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
      certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]

    xpack.security.transport.ssl:
      enabled: true
      key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
      certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
      certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
      verification_mode: certificate
