apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /usr/share/filebeat/logs/services/*.log

    output.logstash:
      hosts: ["logstash:${LOGSTASH_PORT}"]
      ssl:
        certificate_authorities: ["/usr/share/filebeat/config/certs/ca/ca.crt"]
        certificate: "/usr/share/filebeat/config/certs/filebeat/filebeat.crt"
        key: "/usr/share/filebeat/config/certs/filebeat/filebeat.key"
