services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    environment:
      - ELASTIC_PORT=${ELASTIC_PORT}
      - ELASTICSEARCH_SERVICE_TOKEN=${ELASTICSEARCH_SERVICE_TOKEN}
      - XPACK_SECURITY_ENCRYPTIONKEY=${KIBANA_SECURITY_ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${KIBANA_REPORTING_ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_SAVEDOBJECTS_ENCRYPTION_KEY}
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
      - kibana-data:/usr/share/kibana/data
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    env_file:
      - ".env"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    environment:
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    depends_on:
      - logstash
    volumes:
      - ../logs:/logs
      - ./certs:/usr/share/filebeat/certs
      - filebeat-data:/usr/share/filebeat/data
    networks:
      - elk

volumes:
  esdata:
  filebeat-data:
  kibana-data:

networks:
  elk:
    driver: bridge
