apiVersion: v1
kind: ConfigMap
metadata:
  name: gamecatalog-config
data:
  application.yaml: |
    service:
        name: Gamecatalog

    server:
        port: 9094
        error:
            include-message: always

    spring:
        application:
            name: GAME-CATALOG-SERVICE
        datasource:
            url: jdbc:postgresql://${DATABASE_URL}/games
            username: ${DATABASE_USERNAME}
            password: ${DATABASE_PASSWORD}
        jpa:
            hibernate:
                ddl-auto: update
            show-sql: true
            properties:
                hibernate:
                    format_sql: true
                    dialect: org.hibernate.dialect.PostgreSQLDialect
        kafka:
            bootstrap-servers: ${KAFKA_SERVER_ADDRESS}
        security:
            oauth2:
              resourceserver:
                jwt:
                    issuer-uri: ${JWT_ISSUER_URI}
                    jwk-set-uri: ${JWT_ISSUER_URI}/protocol/openid-connect/certs

    eureka:
        instance:
            prefer-ip-address: false
            hostname: gamecatalog
        client:
            fetch-registry: true
            register-with-eureka: true
            service-url:
                defaultZone: ${EUREKA_SERVER_ADDRESS}

    jwt:
        auth:
            converter:
                resource-id: keycloak-client
                principal-attribute: preferred_username

    logging:
        level:
            org.apache.kafka: ERROR

    rollbar:
        accessToken: ${ROLLBAR_TOKEN}
